### ISSUE TITLE
Use restricive permissions for github actions

### ISSUE THREAD

**Issue by ghost** [qbeyond/.github#4]
**Is your feature request related to a problem? Please describe.**
Checkov fails for `/.github/workflows/docs.yaml` because it is implicitly using `write-all` as a permission.

**Describe the solution you'd like**
We should use the most restrictive permissions possible.

```
name: Documentation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          config-file: .terraform-docs.yml
          git-push: "true"
```
